#!/bin/bash -f

WARTOSC=`dialog --stdout --title "Kalkulator" --backtitle "Kalkulator" --inputbox "Wpisz dzialanie matematyczne oddzielone spacjami, np 2 + 2, sqrt 4" 8 60 `
echo $WARTOSC
WART1=$(echo $WARTOSC | cut -d ' ' -f 1)
DZIALANIE=$(echo $WARTOSC | cut -d ' ' -f 2)
WART2=$(echo $WARTOSC | cut -d ' ' -f 3)

	
if [ $WART1 = 'sqrt' ]
then
RESULT=$(echo "sqrt ( $DZIALANIE )" | bc -l)
dialog --stdout --title "Kalkulator" --backtitle "Kalkulator" --msgbox "$RESULT" 8 60
fi

if [ $DZIALANIE = '+' ]
then
RESULT=$(($WART1+$WART2))
dialog --stdout --title "Kalkulator" --backtitle "Kalkulator" --msgbox "$RESULT" 8 60
fi

if [ $DZIALANIE = '-' ]
then
RESULT=$(($WART1-$WART2))
dialog --stdout --title "Kalkulator" --backtitle "Kalkulator" --msgbox "$RESULT" 8 60
fi

if [ $DZIALANIE = '*' ]
then
RESULT=$(($WART1*$WART2))
dialog --stdout --title "Kalkulator" --backtitle "Kalkulator" --msgbox "$RESULT" 8 60
fi

if [ $DZIALANIE = '/' ]
then
if [ $WART2 = 0 ]; then
dialog --stdout --title "Kalkulator" --backtitle "Kalkulator" --msgbox "Nie dzielimy przez 0!" 8 60
		
	fi
RESULT=$(($WART1/$WART2))
dialog --stdout --title "Kalkulator" --backtitle "Kalkulator" --msgbox "$RESULT" 8 60
fi

